### ISSUE TITLE
CS0117 'VGADriverII' does not contain a definition for 'MemoryCopy'

### ISSUE THREAD

**Issue by prescott2m** [napalmtorch/CosmosVGA#1]
This Is A Error That Happens In The Compiler When I Try To Use The Library, Please Fix This! I Am Using The Exact Same Code In The Example.

**Comment by IzKuipers** [comment]
I've also encountered the same error just now, and I'll see if I can fix it.

Disclaimer: I'm not an active developer of CosmosVGA, just a standalone user.

**Comment by ItsLap** [comment]
Im getting it aswell

**Comment by selkij** [comment]
Me too

**Comment by Mag1cpunch** [comment]
go to VGADriverII.cs and go to bottom and paste this after the ClearColorPalette method:

internal static void MemoryCopy(byte* source, byte* destination, int length)
{
       if (source == null || destination == null)
            throw new ArgumentNullException("Source or destination pointer is null.");

       for (int i = 0; i < length; i++)
       {
            destination[i] = source[i];
       }
}

it should fix it
